import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

export type Lang = "ko" | "zh";

interface LangContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  ko: {
    // App name
    "app.name": "Smart Set Packing",

    // Menu
    "menu.dashboard": "대시보드",
    "menu.upload": "파일 업로드",
    "menu.master": "기준정보 관리",
    "menu.workOrders": "작업지시 관리",
    "menu.tshirt": "티셔츠 제작 관리",
    "menu.tshirtWork": "티셔츠 부착 작업",
    "menu.monitor": "생산/포장 모니터링",
    "menu.defects": "불량/예외 관리",
    "menu.reports": "이력조회/리포트",
    "menu.settings": "시스템 설정",

    // Dashboard
    "dashboard.title": "대시보드",
    "dashboard.desc": "전체 생산·포장·출고 현황을 한눈에 확인합니다",
    "dashboard.daily": "일일",
    "dashboard.weekly": "주간",
    "dashboard.monthly": "월간",
    "dashboard.custom": "기간별",
    "dashboard.periodOrders": "기간 작업지시",
    "dashboard.todayOrders": "오늘 작업지시",
    "dashboard.prodDone": "제작 완료",
    "dashboard.setDone": "세트 완료",
    "dashboard.shipDone": "출고 완료",
    "dashboard.errors": "오류 건수",
    "dashboard.vsPrev": "전일 대비",
    "dashboard.vsTarget": "목표 대비",
    "dashboard.hourlyProd": "시간대별 생산량",
    "dashboard.processProgress": "공정별 진행률",
    "dashboard.machineStatus": "기계 상태",
    "dashboard.uptime": "가동률",
    "dashboard.exceptions": "예외 발생 목록",
    "dashboard.pendingInvoices": "미처리 송장 목록",
    "dashboard.tshirt": "티셔츠",
    "dashboard.card": "카드",
    "dashboard.set": "세트",

    // Process names
    "process.tshirt": "티셔츠 제작",
    "process.card": "카드 포장",
    "process.set": "세트 포장",
    "process.shipping": "택배 출고",
    "process.courier": "택배 포장",
    "process.invoice": "송장 부착",
    "process.done": "완료",

    // Statuses
    "status.running": "가동중",
    "status.paused": "일시정지",
    "status.stopped": "정지",
    "status.error": "오류발생",
    "status.disconnected": "통신끊김",
    "status.waiting": "대기",
    "status.inProgress": "진행중",
    "status.completed": "완료",
    "status.attachDone": "부착완료",
    "status.verifyFail": "검증실패",
    "status.rework": "재작업",
    "status.scanDone": "스캔완료",
    "status.packing": "포장중",
    "status.qrPrinted": "QR인쇄완료",
    "status.ejected": "배출완료",
    "status.matchFail": "매칭실패",
    "status.packDone": "포장완료",
    "status.invoiceWait": "송장대기",
    "status.invoiceDone": "송장출력완료",
    "status.shipDone": "출고완료",
    "status.shipHold": "출고보류",
    "status.unprocessed": "미처리",
    "status.disposed": "폐기",

    // File Upload
    "upload.title": "파일 업로드",
    "upload.desc": "기준 데이터를 업로드하여 검증 기준을 설정합니다",
    "upload.selectType": "업로드 유형 선택",
    "upload.siliconQR": "실리콘 마크 QR",
    "upload.designQR": "디자인 QR",
    "upload.hologramQR": "홀로그램 QR",
    "upload.cardBarcode": "카드 바코드",
    "upload.cardSerial": "카드 일련번호",
    "upload.logo": "로고 이미지",
    "upload.shippingLabel": "택배송장",
    "upload.dropzone": "CSV, XLSX 파일을 드래그하거나 클릭하여 업로드",
    "upload.maxSize": "최대 10MB · 중복/누락/형식 자동 검증",
    "upload.history": "업로드 이력",
    "upload.requiredFields": "필수 항목",
    "upload.fileName": "파일명",
    "upload.type": "유형",
    "upload.totalCount": "등록",
    "upload.successCount": "정상",
    "upload.errorCount": "오류",
    "upload.dateTime": "일시",
    "upload.user": "사용자",

    // Master Data
    "master.title": "기준정보 관리",
    "master.desc": "상품, 디자인, 로고, QR/바코드 기준 데이터 관리",
    "master.product": "상품 마스터",
    "master.design": "디자인 마스터",
    "master.logo": "로고 이미지",
    "master.cardMaster": "카드 마스터",
    "master.qrBarcode": "QR/바코드 기준",
    "master.shipper": "출고처/택배사",
    "master.items": "건",
    "master.lastUpdate": "최종",

    // Work Orders
    "workOrders.title": "작업지시 관리",
    "workOrders.desc": "생산 작업지시를 등록하고 관리합니다",
    "workOrders.create": "작업지시 등록",
    "workOrders.search": "작업지시번호, 상품코드 검색...",
    "workOrders.orderNo": "작업지시번호",
    "workOrders.productCode": "상품코드",
    "workOrders.designCode": "디자인코드",
    "workOrders.qty": "수량",
    "workOrders.workDate": "작업일",
    "workOrders.line": "라인",
    "workOrders.assignee": "담당자",
    "workOrders.status": "상태",
    "workOrders.reworkCol": "재작업",
    "workOrders.reworkAlert": "재작업 대기 건이 있습니다",
    "workOrders.reworkAlertDesc": "불량/예외에서 재작업 큐에 추가된 {n}건이 처리 대기중입니다",
    "workOrders.reworkList": "재작업 목록",
    "workOrders.reworkResolved": "처리완료",

    // T-shirt Production
    "tshirtProd.title": "티셔츠 제작 관리",
    "tshirtProd.desc": "실리콘 마크·디자인·홀로그램 QR 검증 및 부착 관리",
    "tshirtProd.scanLog": "실시간 스캔 로그",
    "tshirtProd.time": "시간",
    "tshirtProd.siliconQR": "실리콘QR",
    "tshirtProd.designQR": "디자인QR",
    "tshirtProd.hologramQR": "홀로그램QR",
    "tshirtProd.productCode": "상품코드",
    "tshirtProd.designCode": "디자인코드",
    "tshirtProd.logoCol": "로고",
    "tshirtProd.result": "판정",

    // T-shirt Work
    "tshirtWork.title": "티셔츠 부착 작업",
    "tshirtWork.desc": "QR을 순서대로 스캔하면 자동 검증됩니다",
    "tshirtWork.selectOrder": "작업할 주문건을 선택하세요",
    "tshirtWork.reset": "초기화",
    "tshirtWork.orderList": "← 주문 목록",
    "tshirtWork.totalOrders": "전체 주문",
    "tshirtWork.inProgress": "진행중",
    "tshirtWork.completed": "완료",
    "tshirtWork.defectTotal": "불량 합계",
    "tshirtWork.pendingOrders": "작업 대기 주문",
    "tshirtWork.completedOrders": "완료된 주문",
    "tshirtWork.autoScan": "자동 검증 스캔",
    "tshirtWork.siliconQR": "실리콘 마크 QR",
    "tshirtWork.designQR": "디자인 QR",
    "tshirtWork.hologramQR": "홀로그램 QR",
    "tshirtWork.scanWaiting": "← 스캔 대기중",
    "tshirtWork.scan": "스캔",
    "tshirtWork.allPass": "전체 검증 통과",
    "tshirtWork.attachDone": "부착 완료",
    "tshirtWork.verifyFail": "검증 실패 — 작업 중단",
    "tshirtWork.restart": "다시 시작",
    "tshirtWork.logoCheck": "로고 확인",
    "tshirtWork.logoConfirmed": "로고 확인됨",
    "tshirtWork.logoWait": "전체 QR 검증 통과 시\n로고가 표시됩니다",
    "tshirtWork.sessionLog": "이번 작업 이력",
    "tshirtWork.doneCount": "건 완료",
    "tshirtWork.order": "주문",
    "tshirtWork.product": "상품",
    "tshirtWork.design": "디자인",
    "tshirtWork.size": "사이즈",
    "tshirtWork.dueDate": "납기",
    "tshirtWork.progressRate": "진행률",
    "tshirtWork.todayTarget": "오늘 목표",
    "tshirtWork.defects": "불량",
    "tshirtWork.priorityHigh": "높음",
    "tshirtWork.priorityMedium": "보통",
    "tshirtWork.priorityLow": "낮음",
    "tshirtWork.verifying": "검증중…",
    "tshirtWork.startVerify": "검증 시작",
    "tshirtWork.attachPossible": "부착 진행 가능",

    // Card Packing
    "cardPacking.title": "카드 포장 관리",
    "cardPacking.desc": "카드 바코드 스캔, 포장기계 동작, QR 인쇄 관리",
    "cardPacking.log": "포장 로그",
    "cardPacking.time": "시간",
    "cardPacking.barcode": "카드바코드",
    "cardPacking.serial": "일련번호",
    "cardPacking.productCode": "상품코드",
    "cardPacking.designCode": "디자인코드",
    "cardPacking.printedQR": "인쇄QR",
    "cardPacking.status": "상태",

    // Set Packing
    "setPacking.title": "세트 포장 관리",
    "setPacking.desc": "티셔츠와 카드의 디자인 매칭 검증 및 세트 포장",
    "setPacking.matchWait": "세트 매칭 대기",
    "setPacking.packDone": "세트 포장 완료",
    "setPacking.matchFail": "매칭 실패",
    "setPacking.matchLog": "세트 매칭 로그",
    "setPacking.time": "시간",
    "setPacking.setId": "Set ID",
    "setPacking.tshirtQR": "티셔츠 QR",
    "setPacking.cardQR": "카드 QR",
    "setPacking.productCode": "상품코드",
    "setPacking.designCode": "디자인코드",
    "setPacking.match": "매칭",
    "setPacking.status": "상태",

    // Shipping
    "shipping.title": "택배 출고 관리",
    "shipping.desc": "세트 완료 상품의 송장 매칭 및 출고 처리",
    "shipping.batchPrint": "일괄 송장 출력",
    "shipping.search": "주문번호, 수취인명 검색...",
    "shipping.orderNo": "주문번호",
    "shipping.setId": "Set ID",
    "shipping.recipient": "수취인",
    "shipping.phone": "연락처",
    "shipping.address": "주소",
    "shipping.product": "상품",
    "shipping.invoiceNo": "송장번호",
    "shipping.status": "상태",
    "shipping.print": "출력",

    // Machines
    "machines.title": "기계 모니터링",
    "machines.desc": "포장기계 가동 상태 및 실시간 모니터링",
    "machines.orderPipeline": "주문별 공정 진행 현황",
    "machines.machineStatus": "기계 상태",
    "machines.speed": "속도",
    "machines.uptime": "가동률",
    "machines.totalWork": "누적 작업량",
    "machines.errorCode": "오류코드",
    "machines.lastComm": "최근 통신",

    // Production Monitor
    "monitor.title": "생산/포장 모니터링",
    "monitor.desc": "주문별 공정 진행, 포장, 출고, 장비 상태를 통합 관리합니다",
    "monitor.tab.pipeline": "주문 진행",
    "monitor.tab.card": "카드 포장",
    "monitor.tab.set": "세트 포장",
    "monitor.tab.shipping": "택배 출고",
    "monitor.tab.machines": "장비 상태",

    // Defects
    "defects.title": "불량/예외 관리",
    "defects.desc": "불량 유형 자동 분류 · 재작업 큐 · 공정별 재시작",
    "defects.register": "예외 등록",
    "defects.photo": "사진",
    "defects.rework": "재작업",
    "defects.dispose": "폐기",
    "defects.qrMismatch": "QR 불일치",
    "defects.duplicateQR": "중복 QR 사용",
    "defects.attachFail": "부착 불량",
    "defects.packFail": "포장 불량",
    "defects.commError": "기계 통신 오류",
    "defects.materialShort": "자재 부족",
    "defects.printFail": "송장 출력 실패",
    "defects.tabAll": "전체",
    "defects.tabQueue": "재작업 큐",
    "defects.tabHistory": "처리 완료",
    "defects.kpiUnprocessed": "미처리",
    "defects.kpiQueued": "재작업 대기",
    "defects.kpiReworkDone": "재작업 완료",
    "defects.kpiDisposed": "폐기",
    "defects.filterAll": "전체",
    "defects.filterHigh": "높음",
    "defects.filterMedium": "보통",
    "defects.filterLow": "낮음",
    "defects.empty": "해당 조건의 불량 건이 없습니다",
    "defects.detailLabel": "상세 내용",
    "defects.assigneeLabel": "담당자",
    "defects.resolvedAt": "처리 시간",
    "defects.restartFrom": "재시작 공정",
    "defects.addToQueue": "재작업 큐 추가",
    "defects.startRework": "재작업 시작",
    "defects.completeRework": "재작업 완료",
    "defects.statusUnprocessed": "미처리",
    "defects.statusQueued": "재작업 대기",
    "defects.statusReworking": "재작업중",
    "defects.statusReworkDone": "재작업 완료",
    "defects.statusDisposed": "폐기",

    // Reports
    "reports.title": "이력조회 / 리포트",
    "reports.desc": "생산 실적, 추적 조회, 통계 리포트",
    "reports.trace": "추적 조회",
    "reports.traceDesc": "QR값, 바코드, Set ID, 송장번호, 주문번호로 전 공정 이력을 추적합니다",
    "reports.searchPlaceholder": "추적 값 입력 (QR, 바코드, Set ID, 송장번호...)",
    "reports.basic": "기본 리포트",
    "reports.dailyProd": "일별 생산 실적",
    "reports.dailyCard": "일별 카드 포장 실적",
    "reports.dailySet": "일별 세트 포장 실적",
    "reports.dailyShip": "일별 출고 실적",
    "reports.machineUptime": "기계별 가동률",
    "reports.defectRate": "불량률 분석",
    "reports.workerOutput": "작업자별 처리량",
    

    // Settings
    "settings.title": "시스템 설정",
    "settings.desc": "사용자, 권한, 알림, 장비, PLC, 센서, 명령, 알람 관리",
    "settings.general": "일반 설정",
    "settings.userMgmt": "사용자 관리",
    "settings.userMgmtDesc": "사용자 계정 및 권한 설정",
    "settings.permissions": "권한 설정",
    "settings.permissionsDesc": "역할별 메뉴 접근 권한 관리",
    "settings.notifications": "알림 설정",
    "settings.notificationsDesc": "알림 조건 및 수신 방법 설정",
    "settings.system": "시스템 설정",
    "settings.systemDesc": "기본 설정 및 연동 관리",
    "settings.add": "추가",
    "settings.equipment": "장비 관리",
    "settings.plcTags": "PLC 태그관리",
    "settings.sensors": "센서/신호 맵",
    "settings.commands": "명령 관리",
    "settings.alarms": "알람 관리",
    "settings.eq.name": "기계명",
    "settings.eq.code": "기계코드",
    "settings.eq.line": "라인",
    "settings.eq.plcIp": "PLC IP",
    "settings.eq.protocol": "프로토콜",
    "settings.eq.gwStatus": "게이트웨이 연결",
    "settings.eq.connected": "연결됨",
    "settings.eq.disconnected": "끊김",
    "settings.plc.tagName": "태그명",
    "settings.plc.address": "주소",
    "settings.plc.dataType": "데이터형",
    "settings.plc.rw": "읽기/쓰기",
    "settings.plc.desc": "설명",
    "settings.plc.allMachines": "전체 기계",
    "settings.sensor.name": "센서명",
    "settings.sensor.plcAddr": "연결 PLC 주소",
    "settings.sensor.normalCond": "정상 조건",
    "settings.sensor.alarmCond": "알람 조건",
    "settings.cmd.name": "명령명",
    "settings.cmd.code": "명령코드",
    "settings.cmd.tag": "PLC 태그",
    "settings.cmd.value": "전송값",
    "settings.cmd.permission": "허용 권한",
    "settings.alarm.name": "알람명",
    "settings.alarm.condition": "발생 조건",
    "settings.alarm.target": "알림 대상",
    "settings.alarm.stop": "정지 여부",
    "settings.alarm.retry": "재시도 여부",
    "settings.inspection": "검수 기준",
    "settings.insp.common": "공통 기준",
    "settings.insp.orderOverride": "주문별 예외",
    "settings.insp.allProcess": "전체 공정",
    "settings.insp.process": "공정",
    "settings.insp.item": "검수 항목",
    "settings.insp.method": "검수 방법",
    "settings.insp.criteria": "기준값",
    "settings.insp.autoStop": "자동 정지",
    "settings.insp.enabled": "활성화",
    "settings.insp.commonHint": "공통 기준은 모든 주문에 기본 적용됩니다. 중량 기준의 최소/최대값을 수정하려면 편집 버튼을 클릭하세요.",
    "settings.insp.searchOrder": "주문번호 또는 주문명 검색",
    "settings.insp.addOverride": "예외 기준 추가",
    "settings.insp.orderId": "주문번호",
    "settings.insp.orderName": "주문명",
    "settings.insp.reason": "변경 사유",
    "settings.insp.noOverrides": "등록된 예외 기준이 없습니다",
    "settings.insp.orderHint": "특수 주문건에 대해 공통 기준과 다른 검수 기준을 설정할 수 있습니다. 예외 기준이 설정된 주문은 해당 기준이 우선 적용됩니다.",

    "common.search": "검색",
    "common.time": "시간",
    "common.items": "개",
    "common.perMin": "개/분",
    "common.language": "언어",
  },

  zh: {
    // App name
    "app.name": "Smart Set Packing",

    // Menu
    "menu.dashboard": "仪表盘",
    "menu.upload": "文件上传",
    "menu.master": "基准信息管理",
    "menu.workOrders": "工单管理",
    "menu.tshirt": "T恤制作管理",
    "menu.tshirtWork": "T恤贴附作业",
    "menu.monitor": "生产/包装监控",
    "menu.defects": "不良/异常管理",
    "menu.reports": "历史查询/报表",
    "menu.settings": "系统设置",

    // Dashboard
    "dashboard.title": "仪表盘",
    "dashboard.desc": "一览所有生产·包装·出库现状",
    "dashboard.daily": "日报",
    "dashboard.weekly": "周报",
    "dashboard.monthly": "月报",
    "dashboard.custom": "自定义",
    "dashboard.periodOrders": "期间工单",
    "dashboard.todayOrders": "今日工单",
    "dashboard.prodDone": "制作完成",
    "dashboard.setDone": "套装完成",
    "dashboard.shipDone": "出库完成",
    "dashboard.errors": "异常数量",
    "dashboard.vsPrev": "与前日对比",
    "dashboard.vsTarget": "与目标对比",
    "dashboard.hourlyProd": "每小时产量",
    "dashboard.processProgress": "各工序进度",
    "dashboard.machineStatus": "设备状态",
    "dashboard.uptime": "运行率",
    "dashboard.exceptions": "异常列表",
    "dashboard.pendingInvoices": "待处理运单",
    "dashboard.tshirt": "T恤",
    "dashboard.card": "卡片",
    "dashboard.set": "套装",

    // Process names
    "process.tshirt": "T恤制作",
    "process.card": "卡片包装",
    "process.set": "套装包装",
    "process.shipping": "快递出库",
    "process.courier": "快递包装",
    "process.invoice": "运单贴附",
    "process.done": "完成",

    // Statuses
    "status.running": "运行中",
    "status.paused": "暂停",
    "status.stopped": "停止",
    "status.error": "异常",
    "status.disconnected": "通信中断",
    "status.waiting": "待机",
    "status.inProgress": "进行中",
    "status.completed": "完成",
    "status.attachDone": "贴附完成",
    "status.verifyFail": "验证失败",
    "status.rework": "返工",
    "status.scanDone": "扫描完成",
    "status.packing": "包装中",
    "status.qrPrinted": "QR打印完成",
    "status.ejected": "排出完成",
    "status.matchFail": "匹配失败",
    "status.packDone": "包装完成",
    "status.invoiceWait": "待打印运单",
    "status.invoiceDone": "运单已打印",
    "status.shipDone": "已出库",
    "status.shipHold": "出库暂停",
    "status.unprocessed": "未处理",
    "status.disposed": "报废",

    // File Upload
    "upload.title": "文件上传",
    "upload.desc": "上传基准数据以设定验证标准",
    "upload.selectType": "选择上传类型",
    "upload.siliconQR": "硅胶标QR",
    "upload.designQR": "设计QR",
    "upload.hologramQR": "全息QR",
    "upload.cardBarcode": "卡片条码",
    "upload.cardSerial": "卡片序列号",
    "upload.logo": "Logo图片",
    "upload.shippingLabel": "快递运单",
    "upload.dropzone": "拖拽或点击上传 CSV, XLSX 文件",
    "upload.maxSize": "最大10MB · 自动检测重复/缺失/格式错误",
    "upload.history": "上传历史",
    "upload.requiredFields": "必填项",
    "upload.fileName": "文件名",
    "upload.type": "类型",
    "upload.totalCount": "总数",
    "upload.successCount": "正常",
    "upload.errorCount": "异常",
    "upload.dateTime": "时间",
    "upload.user": "用户",

    // Master Data
    "master.title": "基准信息管理",
    "master.desc": "商品、设计、Logo、QR/条码基准数据管理",
    "master.product": "商品主数据",
    "master.design": "设计主数据",
    "master.logo": "Logo图片",
    "master.cardMaster": "卡片主数据",
    "master.qrBarcode": "QR/条码基准",
    "master.shipper": "出库方/快递公司",
    "master.items": "条",
    "master.lastUpdate": "最后更新",

    // Work Orders
    "workOrders.title": "工单管理",
    "workOrders.desc": "登记并管理生产工单",
    "workOrders.create": "创建工单",
    "workOrders.search": "搜索工单号、商品代码...",
    "workOrders.orderNo": "工单编号",
    "workOrders.productCode": "商品代码",
    "workOrders.designCode": "设计代码",
    "workOrders.qty": "数量",
    "workOrders.workDate": "作业日",
    "workOrders.line": "产线",
    "workOrders.assignee": "负责人",
    "workOrders.status": "状态",
    "workOrders.reworkCol": "返工",
    "workOrders.reworkAlert": "有待处理的返工项",
    "workOrders.reworkAlertDesc": "从不良/异常添加到返工队列的 {n} 件正在等待处理",
    "workOrders.reworkList": "返工列表",
    "workOrders.reworkResolved": "已处理",

    // T-shirt Production
    "tshirtProd.title": "T恤制作管理",
    "tshirtProd.desc": "硅胶标·设计·全息QR验证及贴附管理",
    "tshirtProd.scanLog": "实时扫描日志",
    "tshirtProd.time": "时间",
    "tshirtProd.siliconQR": "硅胶QR",
    "tshirtProd.designQR": "设计QR",
    "tshirtProd.hologramQR": "全息QR",
    "tshirtProd.productCode": "商品代码",
    "tshirtProd.designCode": "设计代码",
    "tshirtProd.logoCol": "Logo",
    "tshirtProd.result": "判定",

    // T-shirt Work
    "tshirtWork.title": "T恤贴附作业",
    "tshirtWork.desc": "按顺序扫描QR即可自动验证",
    "tshirtWork.selectOrder": "请选择要处理的订单",
    "tshirtWork.reset": "重置",
    "tshirtWork.orderList": "← 订单列表",
    "tshirtWork.totalOrders": "全部订单",
    "tshirtWork.inProgress": "进行中",
    "tshirtWork.completed": "完成",
    "tshirtWork.defectTotal": "不良合计",
    "tshirtWork.pendingOrders": "待处理订单",
    "tshirtWork.completedOrders": "已完成订单",
    "tshirtWork.autoScan": "自动验证扫描",
    "tshirtWork.siliconQR": "硅胶标QR",
    "tshirtWork.designQR": "设计QR",
    "tshirtWork.hologramQR": "全息QR",
    "tshirtWork.scanWaiting": "← 等待扫描",
    "tshirtWork.scan": "扫描",
    "tshirtWork.allPass": "全部验证通过",
    "tshirtWork.attachDone": "贴附完成",
    "tshirtWork.verifyFail": "验证失败 — 作业中断",
    "tshirtWork.restart": "重新开始",
    "tshirtWork.logoCheck": "Logo确认",
    "tshirtWork.logoConfirmed": "Logo已确认",
    "tshirtWork.logoWait": "全部QR验证通过后\n显示Logo",
    "tshirtWork.sessionLog": "本次作业记录",
    "tshirtWork.doneCount": "件完成",
    "tshirtWork.order": "订单",
    "tshirtWork.product": "商品",
    "tshirtWork.design": "设计",
    "tshirtWork.size": "尺码",
    "tshirtWork.dueDate": "交期",
    "tshirtWork.progressRate": "进度",
    "tshirtWork.todayTarget": "今日目标",
    "tshirtWork.defects": "不良",
    "tshirtWork.priorityHigh": "高",
    "tshirtWork.priorityMedium": "中",
    "tshirtWork.priorityLow": "低",
    "tshirtWork.verifying": "验证中…",
    "tshirtWork.startVerify": "开始验证",
    "tshirtWork.attachPossible": "可以贴附",

    // Card Packing
    "cardPacking.title": "卡片包装管理",
    "cardPacking.desc": "卡片条码扫描、包装机运行、QR打印管理",
    "cardPacking.log": "包装日志",
    "cardPacking.time": "时间",
    "cardPacking.barcode": "卡片条码",
    "cardPacking.serial": "序列号",
    "cardPacking.productCode": "商品代码",
    "cardPacking.designCode": "设计代码",
    "cardPacking.printedQR": "打印QR",
    "cardPacking.status": "状态",

    // Set Packing
    "setPacking.title": "套装包装管理",
    "setPacking.desc": "T恤与卡片设计匹配验证及套装包装",
    "setPacking.matchWait": "等待套装匹配",
    "setPacking.packDone": "套装包装完成",
    "setPacking.matchFail": "匹配失败",
    "setPacking.matchLog": "套装匹配日志",
    "setPacking.time": "时间",
    "setPacking.setId": "Set ID",
    "setPacking.tshirtQR": "T恤QR",
    "setPacking.cardQR": "卡片QR",
    "setPacking.productCode": "商品代码",
    "setPacking.designCode": "设计代码",
    "setPacking.match": "匹配",
    "setPacking.status": "状态",

    // Shipping
    "shipping.title": "快递出库管理",
    "shipping.desc": "套装完成商品的运单匹配及出库处理",
    "shipping.batchPrint": "批量打印运单",
    "shipping.search": "搜索订单号、收件人...",
    "shipping.orderNo": "订单号",
    "shipping.setId": "Set ID",
    "shipping.recipient": "收件人",
    "shipping.phone": "联系电话",
    "shipping.address": "地址",
    "shipping.product": "商品",
    "shipping.invoiceNo": "运单号",
    "shipping.status": "状态",
    "shipping.print": "打印",

    // Machines
    "machines.title": "设备监控",
    "machines.desc": "包装设备运行状态及实时监控",
    "machines.orderPipeline": "各订单工序进度",
    "machines.machineStatus": "设备状态",
    "machines.speed": "速度",
    "machines.uptime": "运行率",
    "machines.totalWork": "累计产量",
    "machines.errorCode": "异常代码",
    "machines.lastComm": "最近通信",

    // Production Monitor
    "monitor.title": "生产/包装监控",
    "monitor.desc": "订单工序进度、包装、出库、设备状态统一管理",
    "monitor.tab.pipeline": "订单进度",
    "monitor.tab.card": "卡片包装",
    "monitor.tab.set": "套装包装",
    "monitor.tab.shipping": "快递出库",
    "monitor.tab.machines": "设备状态",

    // Defects
    "defects.title": "不良/异常管理",
    "defects.desc": "不良类型自动分类 · 返工队列 · 按工序重启",
    "defects.register": "登记异常",
    "defects.photo": "照片",
    "defects.rework": "返工",
    "defects.dispose": "报废",
    "defects.qrMismatch": "QR不匹配",
    "defects.duplicateQR": "重复QR",
    "defects.attachFail": "贴附不良",
    "defects.packFail": "包装不良",
    "defects.commError": "设备通信异常",
    "defects.materialShort": "材料不足",
    "defects.printFail": "运单打印失败",
    "defects.tabAll": "全部",
    "defects.tabQueue": "返工队列",
    "defects.tabHistory": "处理完成",
    "defects.kpiUnprocessed": "未处理",
    "defects.kpiQueued": "返工待处理",
    "defects.kpiReworkDone": "返工完成",
    "defects.kpiDisposed": "报废",
    "defects.filterAll": "全部",
    "defects.filterHigh": "高",
    "defects.filterMedium": "中",
    "defects.filterLow": "低",
    "defects.empty": "没有符合条件的不良记录",
    "defects.detailLabel": "详细内容",
    "defects.assigneeLabel": "负责人",
    "defects.resolvedAt": "处理时间",
    "defects.restartFrom": "重启工序",
    "defects.addToQueue": "添加到返工队列",
    "defects.startRework": "开始返工",
    "defects.completeRework": "返工完成",
    "defects.statusUnprocessed": "未处理",
    "defects.statusQueued": "返工待处理",
    "defects.statusReworking": "返工中",
    "defects.statusReworkDone": "返工完成",
    "defects.statusDisposed": "报废",

    // Reports
    "reports.title": "历史查询 / 报表",
    "reports.desc": "生产实绩、追溯查询、统计报表",
    "reports.trace": "追溯查询",
    "reports.traceDesc": "通过QR值、条码、Set ID、运单号、订单号追溯全工序历史",
    "reports.searchPlaceholder": "输入追溯值（QR、条码、Set ID、运单号...）",
    "reports.basic": "基础报表",
    "reports.dailyProd": "日产量报表",
    "reports.dailyCard": "日卡片包装报表",
    "reports.dailySet": "日套装包装报表",
    "reports.dailyShip": "日出库报表",
    "reports.machineUptime": "设备运行率",
    "reports.defectRate": "不良率分析",
    "reports.workerOutput": "作业员产量",
    

    // Settings
    "settings.title": "系统设置",
    "settings.desc": "用户、权限、通知、设备、PLC、传感器、命令、报警管理",
    "settings.general": "通用设置",
    "settings.userMgmt": "用户管理",
    "settings.userMgmtDesc": "用户账号及权限设置",
    "settings.permissions": "权限设置",
    "settings.permissionsDesc": "按角色管理菜单访问权限",
    "settings.notifications": "通知设置",
    "settings.notificationsDesc": "通知条件及接收方式设置",
    "settings.system": "系统设置",
    "settings.systemDesc": "基本设置及集成管理",
    "settings.add": "添加",
    "settings.equipment": "设备管理",
    "settings.plcTags": "PLC标签管理",
    "settings.sensors": "传感器/信号映射",
    "settings.commands": "命令管理",
    "settings.alarms": "报警管理",
    "settings.eq.name": "设备名",
    "settings.eq.code": "设备代码",
    "settings.eq.line": "产线",
    "settings.eq.plcIp": "PLC IP",
    "settings.eq.protocol": "协议",
    "settings.eq.gwStatus": "网关连接",
    "settings.eq.connected": "已连接",
    "settings.eq.disconnected": "已断开",
    "settings.plc.tagName": "标签名",
    "settings.plc.address": "地址",
    "settings.plc.dataType": "数据类型",
    "settings.plc.rw": "读/写",
    "settings.plc.desc": "说明",
    "settings.plc.allMachines": "全部设备",
    "settings.sensor.name": "传感器名",
    "settings.sensor.plcAddr": "PLC地址",
    "settings.sensor.normalCond": "正常条件",
    "settings.sensor.alarmCond": "报警条件",
    "settings.cmd.name": "命令名",
    "settings.cmd.code": "命令代码",
    "settings.cmd.tag": "PLC标签",
    "settings.cmd.value": "发送值",
    "settings.cmd.permission": "权限",
    "settings.alarm.name": "报警名",
    "settings.alarm.condition": "触发条件",
    "settings.alarm.target": "通知对象",
    "settings.alarm.stop": "是否停机",
    "settings.alarm.retry": "是否重试",
    "settings.inspection": "检验标准",
    "settings.insp.common": "通用标准",
    "settings.insp.orderOverride": "订单例外",
    "settings.insp.allProcess": "全部工序",
    "settings.insp.process": "工序",
    "settings.insp.item": "检验项目",
    "settings.insp.method": "检验方法",
    "settings.insp.criteria": "基准值",
    "settings.insp.autoStop": "自动停机",
    "settings.insp.enabled": "启用",
    "settings.insp.commonHint": "通用标准默认应用于所有订单。点击编辑按钮可修改重量基准的最小/最大值。",
    "settings.insp.searchOrder": "搜索订单号或订单名",
    "settings.insp.addOverride": "添加例外标准",
    "settings.insp.orderId": "订单号",
    "settings.insp.orderName": "订单名",
    "settings.insp.reason": "变更原因",
    "settings.insp.noOverrides": "暂无例外标准",
    "settings.insp.orderHint": "可为特殊订单设置与通用标准不同的检验标准。设置了例外标准的订单将优先适用该标准。",

    "common.time": "时间",
    "common.items": "个",
    "common.perMin": "个/分",
    "common.language": "语言",
  },
};

const LangContext = createContext<LangContextValue | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("app-lang") as Lang;
    return saved === "zh" ? "zh" : "ko";
  });

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem("app-lang", l);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[lang][key] ?? key;
  }, [lang]);

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
}
